# LS-DYNA R13 *RIGIDWALL_GEOMETRIC_CYLINDER_ID_DISPLAY_MOTION
# Category: rigidwall
# Auto-generated generic template

*createentity groups name="RIGIDWALL_GEOMETRIC_CYLINDER_ID_DISPLAY_MOTION_{{RWID}}" cardimage=RIGIDWALL_GEOMETRIC_CYLINDER_ID_DISPLAY_MOTION