*KEYWORD
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
*CONTROL_ACCURACY
         0         2                    
*CONTROL_BULK_VISCOSITY
       1.5      0.06         1          
*CONTROL_CONTACT
       0.1        1.         2         2         1         1         2         2
         0         0         0         0        0.         0         0         0
*CONTROL_CPU
        0.         0
*CONTROL_DYNAMIC_RELAXATION
       250     0.002     0.995                             0      0.04          
*CONTROL_ENERGY
         2         2         2         2
*CONTROL_HOURGLASS
         4      0.03
*CONTROL_OUTPUT
         1         0         0         1        0.         0      1000      5000
$         0         0         2        50         0        0.         0         0
$                   0                   0         0         0          
$         0         0
*CONTROL_PARALLEL
         8         0         1         0
*CONTROL_SHELL
       40.         1        -1         0         2         2         1         0
*CONTROL_TERMINATION
       25.         0        0.        0.        0.          
*CONTROL_TIMESTEP
        0.       0.9         0        0.   -6.2E-5         0         0         0
*CONTROL_SOLID
         1                             0                            00          
*CONTROL_MPP_IO_NOD3DUMP
*CONTROL_MPP_IO_NODUMP
*CONTROL_MPP_IO_NOFULL
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
*DATABASE_SECFORC
      0.01         2                    
*DATABASE_RWFORC
      0.01         2                    
*DATABASE_NODOUT
      0.01         2                                        
*DATABASE_ELOUT
      0.01         2                                                            
*DATABASE_GLSTAT
      0.01         2                    
*DATABASE_DEFORC
      0.01         2                    
*DATABASE_MATSUM
      0.01         2                    
*DATABASE_RCFORC
      0.01         2                    
*DATABASE_SLEOUT
      0.01         2                    
*DATABASE_JNTFORC
      0.01         2                    
*DATABASE_BINARY_D3PLOT
         1        66         0         0
         0
*DATABASE_EXTENT_BINARY
        24        24         0         0         1         1         1         1
         0         1         0         1         1         1         0         0
                   0                             0         0                    
         0                                        
*DEFINE_CURVE_TITLE
dt
        66         0        1.        10        0.        0.         0         0
                  0.                 0.1
                 1.4                 0.1
                 1.5                 0.1
                  6.                 0.1
                 6.1                 0.5
                 50.                 0.5
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
*END
