*KEYWORD
*INTERFACE_SPRINGBACK_LSDYNA
$HMNAME LOADCOLS       3PA_SEAT_FOAM                                                            
$HWCOLOR LOADCOLS       3      29
$     PSID      NSHV     FTYPE
        57                    
*CONTACT_AUTOMATIC_SINGLE_SURFACE_ID
$HWCOLOR GROUPS      13      28
        13ASS                                                                   
        49                   2                                                  
                                                                                
                                                                                
$$
$$ Sets Defined In HyperMesh
$$
*SET_PART_LIST
$HMSET
$HMNAME SETS      49set1                                                                    
        49                                                  
   2000676   2000677   2000678   2000679   2000801   2000680   2000681   2000682
   2000683   2000684   2000685   2000686   2000687   2000688   2000631   2000689
   2000632   2000704   2000633   2000705   2000634   2000706   2000635   2000707
   2000636   2000708   2000637   2000709   2000638   2000710   2000639   2000711
   2000640   2000712   2000643   2000713   2000644   5000013   2000714   2000669
   2000670   2000671   2000926   2000672   2000673   2000928   2000674   2000675
*SET_PART_LIST
$HMSET
$HMNAME SETS      57SEAT_FOAM_BACK                                                          
        57                                        MECH      
   5000009   2000926   2000928
*END
