# LS-DYNA R13 *DEFINE_CURVE_COMPENSATION_CONSTRAINT_BEGIN
# Category: define
# Auto-generated generic template

*createentity groups name="DEFINE_CURVE_COMPENSATION_CONSTRAINT_BEGIN_{{LCID}}" cardimage=DEFINE_CURVE_COMPENSATION_CONSTRAINT_BEGIN