# LS-DYNA R13 *DEFINE_STOCHASTIC_VARIATION_PROPERTIES
# Category: define
# Auto-generated generic template

*createentity groups name="DEFINE_STOCHASTIC_VARIATION_PROPERTIES_{{LCID}}" cardimage=DEFINE_STOCHASTIC_VARIATION_PROPERTIES