# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_SCALE_CONTACT_COST
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_SCALE_CONTACT_COST" cardimage=CONTROL_MPP_DECOMPOSITION_SCALE_CONTACT_COST