# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_PARTSET_DISTRIBUTE_LOCAL
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_PARTSET_DISTRIBUTE_LOCAL" cardimage=CONTROL_MPP_DECOMPOSITION_PARTSET_DISTRIBUTE_LOCAL