# LS-DYNA R13 *CONTROL_FORMING_ONESTEP_AUTO_CONSTRAINT
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_FORMING_ONESTEP_AUTO_CONSTRAINT" cardimage=CONTROL_FORMING_ONESTEP_AUTO_CONSTRAINT