# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_DEFORMED_GEOMETRY
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_DEFORMED_GEOMETRY" cardimage=CONTROL_MPP_DECOMPOSITION_DEFORMED_GEOMETRY