# LS-DYNA R13 *CONTROL_IMPLICIT_STATIC_CONDENSATION
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_IMPLICIT_STATIC_CONDENSATION" cardimage=CONTROL_IMPLICIT_STATIC_CONDENSATION