# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_CONTACT_ISOLATE
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_CONTACT_ISOLATE" cardimage=CONTROL_MPP_DECOMPOSITION_CONTACT_ISOLATE