# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_PARTS_DISTRIBUTE
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_PARTS_DISTRIBUTE" cardimage=CONTROL_MPP_DECOMPOSITION_PARTS_DISTRIBUTE