# LS-DYNA R13 *CONTROL_FORMING_AUTOPOSITION_PARAMETER
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_FORMING_AUTOPOSITION_PARAMETER" cardimage=CONTROL_FORMING_AUTOPOSITION_PARAMETER