# LS-DYNA R13 *CONTROL_FORMING_TRIMMING_SOLID_REFINEMENT
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_FORMING_TRIMMING_SOLID_REFINEMENT" cardimage=CONTROL_FORMING_TRIMMING_SOLID_REFINEMENT