# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_ALE_ELE
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_ALE_ELE" cardimage=CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_ALE_ELE