# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS" cardimage=CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS