# LS-DYNA R13 *CONTROL_IMPLICIT_MODAL_DYNAMIC_DAMPING
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_IMPLICIT_MODAL_DYNAMIC_DAMPING" cardimage=CONTROL_IMPLICIT_MODAL_DYNAMIC_DAMPING