# LS-DYNA R13 *CONTROL_FORMING_AUTOPOSITION_PARAMETER_
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_FORMING_AUTOPOSITION_PARAMETER_" cardimage=CONTROL_FORMING_AUTOPOSITION_PARAMETER_