# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_FLAG_STRESS_STRAIN_CURVE
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_FLAG_STRESS_STRAIN_CURVE" cardimage=CONTROL_MPP_DECOMPOSITION_FLAG_STRESS_STRAIN_CURVE