# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_REDECOMPOSITION
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_REDECOMPOSITION" cardimage=CONTROL_MPP_DECOMPOSITION_REDECOMPOSITION