# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_SCALE_FACTOR_SPH
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_SCALE_FACTOR_SPH" cardimage=CONTROL_MPP_DECOMPOSITION_SCALE_FACTOR_SPH