# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_SPH_ELEMENTS
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_SPH_ELEMENTS" cardimage=CONTROL_MPP_DECOMPOSITION_DISTRIBUTE_SPH_ELEMENTS