# LS-DYNA R13 *CONTROL_IMPLICIT_MODAL_DYNAMIC_MODE_OPTION
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_IMPLICIT_MODAL_DYNAMIC_MODE_OPTION" cardimage=CONTROL_IMPLICIT_MODAL_DYNAMIC_MODE_OPTION