# LS-DYNA R13 *CONTROL_IMPLICIT_ROTATIONAL_DYNAMICS
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_IMPLICIT_ROTATIONAL_DYNAMICS" cardimage=CONTROL_IMPLICIT_ROTATIONAL_DYNAMICS