# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS_LOCAL
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS_LOCAL" cardimage=CONTROL_MPP_DECOMPOSITION_ARRANGE_PARTS_LOCAL