# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_TRANSFORMATION
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_TRANSFORMATION" cardimage=CONTROL_MPP_DECOMPOSITION_TRANSFORMATION