# LS-DYNA R13 *CONTROL_FORMING_REMOVE_ADAPTIVE_CONSTRAINTS
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_FORMING_REMOVE_ADAPTIVE_CONSTRAINTS" cardimage=CONTROL_FORMING_REMOVE_ADAPTIVE_CONSTRAINTS