# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_DISABLE_UNREF_CURVES
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_DISABLE_UNREF_CURVES" cardimage=CONTROL_MPP_DECOMPOSITION_DISABLE_UNREF_CURVES