# LS-DYNA R13 *CONTROL_MPP_DECOMPOSITION_CONTACT_DISTRIBUTE_LO
# Category: control
# Auto-generated generic template

*createentity cards name="CONTROL_MPP_DECOMPOSITION_CONTACT_DISTRIBUTE_LO" cardimage=CONTROL_MPP_DECOMPOSITION_CONTACT_DISTRIBUTE_LO