# LS-DYNA R13 *BOUNDARY_ACOUSTIC_IMPEDANCE_MECHANICAL
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_ACOUSTIC_IMPEDANCE_MECHANICAL_{{SID}}" cardimage=BOUNDARY_ACOUSTIC_IMPEDANCE_MECHANICAL