# LS-DYNA R13 *BOUNDARY_PRESCRIBED_MOTION_FINAL_GEOMETRY
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_PRESCRIBED_MOTION_FINAL_GEOMETRY_{{SID}}" cardimage=BOUNDARY_PRESCRIBED_MOTION_FINAL_GEOMETRY