# LS-DYNA R13 *BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION1_
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION1__{{SID}}" cardimage=BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION1_