# LS-DYNA R13 *BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION_{{SID}}" cardimage=BOUNDARY_PRESCRIBED_ORIENTATION_RIGID_OPTION