# LS-DYNA R13 *BOUNDARY_THERMAL_BULKFLOW_OPTION1_OPTION2
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_THERMAL_BULKFLOW_OPTION1_OPTION2_{{SID}}" cardimage=BOUNDARY_THERMAL_BULKFLOW_OPTION1_OPTION2