# LS-DYNA R13 *BOUNDARY_PRESCRIBED_ORIENTATION_VECTOR
# Category: boundary
# Auto-generated generic template

*createentity groups name="BOUNDARY_PRESCRIBED_ORIENTATION_VECTOR_{{SID}}" cardimage=BOUNDARY_PRESCRIBED_ORIENTATION_VECTOR