# LS-DYNA R13 *CONSTRAINED_JOINT_STIFFNESS_GENERALIZED
# Category: constrained
# Auto-generated generic template

*createentity groups name="CONSTRAINED_JOINT_STIFFNESS_GENERALIZED_{{SID}}" cardimage=CONSTRAINED_JOINT_STIFFNESS_GENERALIZED