# LS-DYNA R13 *CONSTRAINED_JOINT_STIFFNESS_CYLINDRICAL
# Category: constrained
# Auto-generated generic template

*createentity groups name="CONSTRAINED_JOINT_STIFFNESS_CYLINDRICAL_{{SID}}" cardimage=CONSTRAINED_JOINT_STIFFNESS_CYLINDRICAL