# LS-DYNA R13 *CONTACT_MPP_DECOMPOSITION_DEFORMED_GEOMETRY
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_MPP_DECOMPOSITION_DEFORMED_GEOMETRY_{{SID}}" cardimage=CONTACT_MPP_DECOMPOSITION_DEFORMED_GEOMETRY