# LS-DYNA R13 *CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURACE_ORTHO_FRIC
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURACE_ORTHO_FRIC_{{SID}}" cardimage=CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURACE_ORTHO_FRIC