# LS-DYNA R13 *CONTACT_AUTOMATIC_SINGLE_SURFACE_TIEBREAK
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_AUTOMATIC_SINGLE_SURFACE_TIEBREAK_{{SID}}" cardimage=CONTACT_AUTOMATIC_SINGLE_SURFACE_TIEBREAK