# LS-DYNA R13 *CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED_{{SID}}" cardimage=CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED