# LS-DYNA R13 *CONTACT_FORMING_SURFACE_TO_SURFACE_MORTAR
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_FORMING_SURFACE_TO_SURFACE_MORTAR_{{SID}}" cardimage=CONTACT_FORMING_SURFACE_TO_SURFACE_MORTAR