# LS-DYNA R13 *CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURFACE_THERMAL_FRICTION_ID
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURFACE_THERMAL_FRICTION_ID_{{SID}}" cardimage=CONTACT_FORMING_ONE_WAY_SURFACE_TO_SURFACE_THERMAL_FRICTION_ID