# LS-DYNA R13 *CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_LUBRICATION
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_LUBRICATION_{{SID}}" cardimage=CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_LUBRICATION