# LS-DYNA R13 *CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED_WELD
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED_WELD_{{SID}}" cardimage=CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_MORTAR_TIED_WELD