# LS-DYNA R13 *CONTACT_TIED_SHELL_EDGE_TO_SURFACE_BEAM_OFFSET
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_TIED_SHELL_EDGE_TO_SURFACE_BEAM_OFFSET_{{SID}}" cardimage=CONTACT_TIED_SHELL_EDGE_TO_SURFACE_BEAM_OFFSET