# LS-DYNA R13 *CONTACT_TIED_NODES_TO_SURFACE_CONSTRAINED_OFFSET
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_TIED_NODES_TO_SURFACE_CONSTRAINED_OFFSET_{{SID}}" cardimage=CONTACT_TIED_NODES_TO_SURFACE_CONSTRAINED_OFFSET