# LS-DYNA R13 *CONTACT_2D_AUTOMATIC_SINGLE_SURFACE_MORTAR
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_2D_AUTOMATIC_SINGLE_SURFACE_MORTAR_{{SID}}" cardimage=CONTACT_2D_AUTOMATIC_SINGLE_SURFACE_MORTAR