# LS-DYNA R13 *CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_TIEBREAK_
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_TIEBREAK__{{SID}}" cardimage=CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_TIEBREAK_