# LS-DYNA R13 *CONTACT_SURFACE_TO_SURFACE_CONTRACTION_JOINT
# Category: contact
# Auto-generated generic template

*createentity groups name="CONTACT_SURFACE_TO_SURFACE_CONTRACTION_JOINT_{{SID}}" cardimage=CONTACT_SURFACE_TO_SURFACE_CONTRACTION_JOINT