# LS-DYNA R13 *EOS_LINEAR_POLYNOMIAL_WITH_ENERGY_LEAK
# Category: eos
# Auto-generated generic template

*createentity mats name="EOS_LINEAR_POLYNOMIAL_WITH_ENERGY_LEAK_{{EOSID}}" cardimage=EOS_LINEAR_POLYNOMIAL_WITH_ENERGY_LEAK