# LS-DYNA R13 *INTERFACE_COMPENSATION_3D_ACCELERATOR
# Category: interface
# Auto-generated generic template

*createentity groups name="INTERFACE_COMPENSATION_3D_ACCELERATOR_{{SID}}" cardimage=INTERFACE_COMPENSATION_3D_ACCELERATOR