# LS-DYNA R13 *INTERFACE_SPRINGBACK_LSDYNA_NOTHICKNESS
# Category: interface
# Auto-generated generic template

*createentity groups name="INTERFACE_SPRINGBACK_LSDYNA_NOTHICKNESS_{{SID}}" cardimage=INTERFACE_SPRINGBACK_LSDYNA_NOTHICKNESS