# LS-DYNA R13 *INTERFACE_THICKNESS_CHANGE_COMPENSATION
# Category: interface
# Auto-generated generic template

*createentity groups name="INTERFACE_THICKNESS_CHANGE_COMPENSATION_{{SID}}" cardimage=INTERFACE_THICKNESS_CHANGE_COMPENSATION