# K file integration script
# Generated by Dyna-mcp
puts "MCP_K_INTEGRATION_START"

*createentity mats name="MAT_PIECEWISE_LINEAR_PLASTICITY_1"
hm_setvalue mats id=1 STATUS=2 MAT_TYPE=PIECEWISE_LINEAR_PLASTICITY
hm_setvalue mats id=1 RHO=7.85e-09
hm_setvalue mats id=1 E=210000.0
hm_setvalue mats id=1 PR=0.3
*createentity mats name="MAT_RIGID_2"
hm_setvalue mats id=2 STATUS=2 MAT_TYPE=RIGID
hm_setvalue mats id=2 RHO=7.85e-09
hm_setvalue mats id=2 E=210000.0
hm_setvalue mats id=2 PR=0.3
*createentity props name="SECTION_SHELL_1"
hm_setvalue props id=1 STATUS=2 SECTION_TYPE=SHELL
hm_setvalue props id=1 ELFORM=0
hm_setvalue props id=1 SHRF=0.0
*createentity props name="SECTION_SHELL_2"
hm_setvalue props id=2 STATUS=2 SECTION_TYPE=SHELL
hm_setvalue props id=2 ELFORM=0
hm_setvalue props id=2 SHRF=0.0
*createnode 0.0 0.0 0.0 0 0 0
*createnode 10.0 0.0 0.0 0 0 0
*createnode 10.0 10.0 0.0 0 0 0
*createnode 0.0 10.0 0.0 0 0 0
*createnode 5.0 5.0 2.0 0 0 0
*createnode 6.0 5.0 2.0 0 0 0
*createnode 6.0 6.0 2.0 0 0 0
*createnode 5.0 6.0 2.0 0 0 0
*createentity groups name="SET_PART_LIST_1"
hm_setvalue groups id=1 STATUS=2 GROUP_TYPE=SET
hm_setvalue groups id=1 CARD_IMAGE=SET_PART_LIST
*createentity groups name="SET_PART_LIST_2"
hm_setvalue groups id=2 STATUS=2 GROUP_TYPE=SET
hm_setvalue groups id=2 CARD_IMAGE=SET_PART_LIST
*createentity groups name="SET_NODE_LIST_3"
hm_setvalue groups id=3 STATUS=2 GROUP_TYPE=SET
hm_setvalue groups id=3 CARD_IMAGE=SET_NODE_LIST
*createentity groups name="SET_SEGMENT_4"
hm_setvalue groups id=4 STATUS=2 GROUP_TYPE=SET
hm_setvalue groups id=4 CARD_IMAGE=SET_SEGMENT
*createentity groups name="SET_SEGMENT_5"
hm_setvalue groups id=5 STATUS=2 GROUP_TYPE=SET
hm_setvalue groups id=5 CARD_IMAGE=SET_SEGMENT
*createentity groups name="BC_SPC_SET_3"
hm_setvalue groups id=3 STATUS=2 GROUP_TYPE=BOUNDARY
hm_setvalue groups id=3 CARD_IMAGE=BOUNDARY_SPC_SET
hm_setvalue groups id=3 DOFX=1
hm_setvalue groups id=3 DOFY=1
hm_setvalue groups id=3 DOFZ=1
hm_setvalue groups id=3 DOFRX=1
hm_setvalue groups id=3 DOFRY=1
hm_setvalue groups id=3 DOFRZ=1
*createentity groups name="CONTACT_AUTOMATIC_SURFACE_TO_SURFACE_5_4"
hm_setvalue groups id=5 STATUS=2 GROUP_TYPE=CONTACT
hm_setvalue groups id=5 CARD_IMAGE=CONTACT_AUTOMATIC_SURFACE_TO_SURFACE

puts "MCP_K_INTEGRATION_END"
*writefile "F:/Dyna-mcp/output/model_from_k.hm" 1
puts "MODEL_SAVED"
